### ISSUE TITLE
大佬想用你模板。但是没有语雀会员，只能用账号密码，action不会写。。。可以更新下吗，notion也行啊

### ISSUE THREAD

**Issue by xinkeji** [ccknbc-actions/blog-butterfly#174]
大佬想用你模板。但是没有语雀会员，只能用账号密码，action不会写。。。可以更新下吗，notion也行啊

**Comment by CCKNBC** [comment]
在elog目录下其实是有配置的，你只需要更改一下 package.json中的命令，改为对应模式的命令，Actions同样更改一下所需要的环境变量就好啦，如果还不会可以再问我

**Comment by xinkeji** [comment]
> 在elog目录下其实是有配置的，你只需要更改一下 package.json中的命令，改为对应模式的命令，Actions同样更改一下所需要的环境变量就好啦，如果还不会可以再问我

😂😂😂😂我是个代码小白，昨天发现您的代码，昨天兴奋的基本上一夜没睡到四点多（主要是忙那个action），目前就本地能正常生成网页，但是到github上就action生成不了了

**Comment by xinkeji** [comment]
> > 在elog目录下其实是有配置的，你只需要更改一下 package.json中的命令，改为对应模式的命令，Actions同样更改一下所需要的环境变量就好啦，如果还不会可以再问我
> 
> 😂😂😂😂我是个代码小白，昨天发现您的代码，昨天兴奋的基本上一夜没睡到四点多（主要是忙那个action），目前就本地能正常生成网页，但是到github上就action生成不了了

可以抽空改下嘛😫

**Comment by CCKNBC** [comment]
> > > 在elog目录下其实是有配置的，你只需要更改一下 package.json中的命令，改为对应模式的命令，Actions同样更改一下所需要的环境变量就好啦，如果还不会可以再问我
> > 
> > 😂😂😂😂我是个代码小白，昨天发现您的代码，昨天兴奋的基本上一夜没睡到四点多（主要是忙那个action），目前就本地能正常生成网页，但是到github上就action生成不了了
> 
> 可以抽空改下嘛😫

可以看一下这边文章结尾部分，要注意的点是因为用到了备份代码，需要注释掉后面的再取消注释，也就是需要跑两次才可以

https://blog.ccknbc.cc/posts/yuque-to-hexo/

问题是我这边没有要改的地方，Actions需要的环境变量本来就有写，我不知道你让我改什么

**Comment by xinkeji** [comment]
![mmexport1705301629932.png](https://github.com/ccknbc-actions/blog-butterfly/assets/33138729/6b35d78b-4a3e-4653-85c7-6f7837515b1f)

是这样的，我直接把yuque-token.js直接改成密码版本了（因为没有找到改文件的位置），
然后后面就出错了

**Comment by CCKNBC** [comment]
https://www.imql.life/2023/08/12/Writing_on_The_Cloud_With_YuQue/

别人根据我的仓库写的教程 比较详细，可做参考和理解

**Comment by xinkeji** [comment]
感谢感谢，感谢大佬，马上看，然后想问下是不是改成运行yuque-pwd.js就可以了，如果是的，请问下action那个运行让运行yuque-token的文件在哪里改



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月15日(周一) 下午3:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ccknbc-actions/blog-butterfly] 大佬想用你模板。但是没有语雀会员，只能用账号密码，action不会写。。。可以更新下吗，notion也行啊 (Issue #174)




 
https://www.imql.life/2023/08/12/Writing_on_The_Cloud_With_YuQue/
 
别人根据我的仓库写的教程 比较详细，可做参考和理解

**Comment by CCKNBC** [comment]
我不是说在 package.json 中改掉命令 elog: 那一步改为 运行pwb就好 Actions 就不用动啊 都配置好的 只是备份的话需要根据他的教程改一改 做初始化

**Comment by xinkeji** [comment]
懂了懂了，这些



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月15日(周一) 下午3:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ccknbc-actions/blog-butterfly] 大佬想用你模板。但是没有语雀会员，只能用账号密码，action不会写。。。可以更新下吗，notion也行啊 (Issue #174)




 
我不是说在 package.json 中改掉命令 elog: 那一步改为 运行pwb就好 Actions 就不用动啊 都配置好的 只是备份的话需要根据他的教程改一改 做初始化

**Comment by xinkeji** [comment]
我还在弄，太复杂了，但是代码真的牛逼



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月15日(周一) 下午3:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ccknbc-actions/blog-butterfly] 大佬想用你模板。但是没有语雀会员，只能用账号密码，action不会写。。。可以更新下吗，notion也行啊 (Issue #174)




 
我不是说在 package.json 中改掉命令 elog: 那一步改为 运行pwb就好 Actions 就不用动啊 都配置好的 只是备份的话需要根据他的教程改一改 做初始化

**Comment by xinkeji** [comment]
大佬，有空的时候看下，这个怎么搞啊

**Comment by xinkeji** [comment]
搞定了搞定了，这些大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月15日(周一) 下午3:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ccknbc-actions/blog-butterfly] 大佬想用你模板。但是没有语雀会员，只能用账号密码，action不会写。。。可以更新下吗，notion也行啊 (Issue #174)




 
我不是说在 package.json 中改掉命令 elog: 那一步改为 运行pwb就好 Actions 就不用动啊 都配置好的 只是备份的话需要根据他的教程改一改 做初始化

**Comment by CCKNBC** [comment]
最后，麻烦改掉我的相关配置和功能，以及页面

**Comment by xinkeji** [comment]
在改，昨天太晚了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月16日(周二) 上午8:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ccknbc-actions/blog-butterfly] 大佬想用你模板。但是没有语雀会员，只能用账号密码，action不会写。。。可以更新下吗，notion也行啊 (Issue #174)




 
最后，麻烦改掉我的相关配置和功能，以及页面

**Comment by xinkeji** [comment]
大佬，这个需要设置hexo-neat嘛



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月16日(周二) 上午8:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ccknbc-actions/blog-butterfly] 大佬想用你模板。但是没有语雀会员，只能用账号密码，action不会写。。。可以更新下吗，notion也行啊 (Issue #174)




 
最后，麻烦改掉我的相关配置和功能，以及页面

**Comment by CCKNBC** [comment]
你怎么用是你的事，我只是公开我的代码，给有需要的人参考，会用的人一看就懂

**Comment by xinkeji** [comment]
好的，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月16日(周二) 上午9:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ccknbc-actions/blog-butterfly] 大佬想用你模板。但是没有语雀会员，只能用账号密码，action不会写。。。可以更新下吗，notion也行啊 (Issue #174)




 
你怎么用是你的事，我只是公开我的代码，给有需要的人参考，会用的人一看就懂

**Comment by xinkeji** [comment]
我直接换了个主题，不然改的太慢了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月16日(周二) 上午9:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ccknbc-actions/blog-butterfly] 大佬想用你模板。但是没有语雀会员，只能用账号密码，action不会写。。。可以更新下吗，notion也行啊 (Issue #174)




 
你怎么用是你的事，我只是公开我的代码，给有需要的人参考，会用的人一看就懂
